### ISSUE TITLE
How to change the port from 443 to 8000? I am trying to run the setup on my Linux server.

### ISSUE THREAD

**Issue by satcit-me** [keldenl/gpt-llama.cpp#19]
"Linux - Port :443 blocked by default, may have to change the port to 8000 to get working"

How to do this? Sorry. I am a newbie

**Comment by fredroo** [comment]
index.js const PORT = 443; line 11 change for 8000 and be happy @satcit-me, if you update, this change is gone

**Comment by keldenl** [comment]
just pushed a change to make this easier. run `PORT=8000 npm run start` to run if off that port!

make sure to pull my latest changes~ also try running `sh ./test-installation.sh` to test ur config

**Comment by fredroo** [comment]
@keldenl nice update

**Comment by keldenl** [comment]
@satcit-me lmk if u got it working, if so, i'll go-ahead and close it

**Comment by keldenl** [comment]
Closing this as the PORT was added as a supported env var.
